### ISSUE TITLE
Could not find a version that satisfies the requirement bidict>=0.21.0

### ISSUE THREAD

**Issue by new-soul** [supergreenlab/SuperGreenOS#4]
I know the problem is the python version.
As python2.7 the max version of bidict is 0.18.4 and python 3 is 0.21.2

I installed the /Users/Soul/esp/esp-idf/requirements.tx libs on mac os but it was report the problem.

The following Python requirements are not satisfied:
click>=5.0
pyelftools>=0.22
gdbgui==0.13.2.0
pygdbmi<=0.9.0.2
reedsolo>=1.5.3,<=1.5.4
bitstring>=3.1.6
ecdsa>=0.16.0
To install the missing packages, please run "/Users/Soul/esp/esp-idf/install.sh"
Diagnostic information:
...
make: *** No rule to make target `/Users/Soul/esp/SuperGreenOS/build/include/config/auto.conf', needed by `/Users/Soul/esp/SuperGreenOS/build/bootloader/bootloader.bin'.  Stop.

How can I fix the mistake and flash in esp32?
Thanks.

**Comment by vitaminwater** [comment]
Hey sorry for the late reply.

I think you might need to use virtualenv to avoid conflicts with the system installation of python.
Also, but I'm not sure because I don't use mac so much anymore, but if you use brew make sure you're not using the pre-installed python. I remember it could be a problem.
